name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: 🧪 Validar Código e Imagen Docker
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código fuente
        uses: actions/checkout@v4

      - name: Validar sintaxis del Dockerfile
        run: docker build -t test-image .

      - name: Confirmación de pruebas pasadas
        run: echo "¡Validaciones completadas con éxito! Listo para producción."

  deploy-to-render:
    name: 🚀 Desplegar en Render
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Disparar Deploy Hook en Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
          echo "¡Orden de despliegue enviada a Render!"